-- AlterTable
ALTER TABLE "Mood" ALTER COLUMN "gdb" DROP NOT NULL,
ALTER COLUMN "zt_num" DROP NOT NULL,
ALTER COLUMN "zt_fbl" DROP NOT NULL,
ALTER COLUMN "dt_num" DROP NOT NULL,
ALTER COLUMN "dt_fbl" DROP NOT NULL,
ALTER COLUMN "zt_jjl" DROP NOT NULL,
ALTER COLUMN "high_100" DROP NOT NULL,
ALTER COLUMN "dm_num" DROP NOT NULL,
ALTER COLUMN "ths_mood" DROP NOT NULL,
ALTER COLUMN "all_vol" DROP NOT NULL,
ALTER COLUMN "zt_vol" DROP NOT NULL,
ALTER COLUMN "zr_jsy" DROP NOT NULL,
ALTER COLUMN "bx" DROP NOT NULL;
